
"""empty message

Revision ID: e8544cf52a70
Revises: a86fd2af23d8
Create Date: 2020-10-12 03:49:35.595987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8544cf52a70'
down_revision = 'a86fd2af23d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Venue', 'City', ['city_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    # ### end Alembic commands ###
